Update Fork (#6)
* Check scm type empty for comm editor (#207)

* fix: check trigger type against repo url

* fix: fail if script is not successful

* Update task-discovery.yaml

* Update README.md

* Update task-discovery.yaml

* Update task-discovery.yaml

* Update task-bom.yaml

* Update task-bom.yaml

* Update task-bom.yaml

* fix: switch case for if statement

* feat: update discovery image

* Update task-discovery.yaml

* feat: update discovery image

* fix: update cis image, update discovery

* feat: update vuln image

* Update task-vulnerability-remediation.yaml

* Update task-terraform-compliance.yaml

* fix: scm check to fix ci

* fix: spacing

* fix: images

* Update task-terraform-compliance.yaml

Co-authored-by: darosale <darosale@us.ibm.com@darosales-MBP.localdomain>
Co-authored-by: darosale <darosale@us.ibm.com@darosales-MBP.attlocal.net>

* Add oc login for ROKS cluster

* Update CRA images (#208)

* fix: update images

* fix: update terraform, not comm-editor

Co-authored-by: darosale <darosale@us.ibm.com@darosales-MBP.attlocal.net>

Co-authored-by: David Rosales <darosale@us.ibm.com>
Co-authored-by: darosale <darosale@us.ibm.com@darosales-MBP.localdomain>
Co-authored-by: darosale <darosale@us.ibm.com@darosales-MBP.attlocal.net>
Co-authored-by: jaunin-b <jaunin.b@fr.ibm.com>

diff --git a/cra/task-terraform-compliance.yaml b/cra/task-terraform-compliance.yaml
--- a/cra/task-terraform-compliance.yaml
+++ b/cra/task-terraform-compliance.yaml
@@ -326,6 +326,29 @@ spec:
             esac
           fi
 
+          if [ -n "$(params.scm-type)" ]; then
+            case "$(params.repository)" in
+              *git.cloud.ibm.com*)
+                if [ "$(params.scm-type)" != "gitlab" ]; then
+                  echo "Error: Trigger type '$(params.scm-type)' expected to be gitlab"
+                  exit 1
+                fi
+                ;;
+              *ibm.com*)
+                if [ "$(params.scm-type)" != "github-ent" ]; then
+                  echo "Error: Trigger type '$(params.scm-type)' expected to be github-ent"
+                  exit 1
+                fi
+                ;;
+              *)
+                if [ "$(params.scm-type)" != "github" ]; then
+                  echo "Error: Trigger type '$(params.scm-type)' expected to be github"
+                  exit 1
+                fi
+                ;;
+            esac
+          fi
+
           /usr/local/bin/comm-editor \
             -repo-url "$(params.repository)" \
             -pr-url "$(params.pr-url)" \
